spring.application.name=inventory

# PostgreSQL connection (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7n1qbaqqhas73fkn5v0-a:5432/inventory_x6bv
spring.datasource.username=inventory_x6bv_user
spring.datasource.password=PqDnhBKuIrfVU0e1Ky0xY6VWxajkYXdV

# JPA settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect